[project]
name = "scraper"
version = "0.1.0"
description = ""
dependencies = ["requests", "bs4", "markdownify", "tenacity", "utils"]
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
dev-dependencies = []

[tool.uv.sources]
utiuls = { workspace = true }
